global:
  message: Microservices Environment!

logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defaultZone: http://mysql:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
