spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/order_master
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
